VENV=.venv

# All commands live in noxfile.py. The Makefile is a thin wrapper around it.
NOX=nox

.PHONY: help
help:
	@echo "venv         -> prepare VENV with all dependencies installed"
	@echo "test         -> run tests on all supported Python versions"
	@echo "lint         -> check the code with ruff (no changes are made)"
	@echo "fmt          -> format the code with ruff"
	@echo "cov          -> run tests coverage, report to stdout and prepare XML and HTML reports"
	@echo "check        -> run tests and lint checks"
	@echo "clean        -> remove autogenerated files (venv, cache, etc.)"
	@echo ""
	@echo "Requires uv and nox with nox-uv: uv tool install nox --with nox-uv"

$(VENV):
	uv sync --all-groups

.PHONY: venv
venv: $(VENV)

.PHONY: test
test:
	$(NOX) -s tests

.PHONY: lint
lint:
	$(NOX) -s lint

.PHONY: fmt
fmt:
	$(NOX) -s fmt

.PHONY: cov
cov:
	$(NOX) -s coverage

.PHONY: check
check:
	$(NOX) -s lint tests

.PHONY: clean
clean:
	rm -rf $(VENV) build _build dist *.egg-info .coverage coverage.xml htmlcov .nox .mypy_cache .ruff_cache
	find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete
	py3clean . -v
