[tool.poetry]
name = "csobpg"
version = "0.6.0"
description = "Library for communication with ČSOB API"
authors = ["Andrii Nechaiev <andrewnech@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/litteratum/csobpg"
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries",
    "License :: OSI Approved :: MIT License",
    "Operating System :: POSIX :: Linux",
    "Topic :: Utilities",
]

[tool.poetry.dependencies]
python = "^3.9"
pycryptodome = "^3.17"
httprest = "^0.3"

[tool.poetry.group.test.dependencies]
pytest = "^8"
pytest-cov = "^6"
responses = "^0.25.7"
freezegun = "^1.5.1"

[tool.poetry.group.lint.dependencies]
ruff = "^0.16.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 79
target-version = "py39"

[tool.ruff.lint]
flake8-pytest-style.parametrize-names-type = "list"
select = ["ALL"]
ignore = [
    "ANN",      # flake8-annotations

    "D102",     # Missing docstring in a public method is OK
    "D105",     # Missing docstring in a magic method is OK
    "D107",     # Missing docstring in __init__ is OK

    "D203",     # Conflicts with D211. We want to start docstrings from a first line, not a second one
    "D213",     # Conflicts with D212. We want to start multiline docstrings from a first line, not a second one
    "D413",     # Missing blank line after last section is OK

    "EM101",    # String literals in exceptions are OK
    "EM102",    # Similar to EM101, but for f-strings
    "TRY003",   # Long error messages in exceptions are OK
    "TRY400",   # It is OK to use logging.error() for logging exceptions
    "BLE001",   # It is OK to catch Exception

    "PLR0911",  # Too many return statements. Sometimes unavoidable. Use common sense
    "PLR0912",  # Too many branches. Sometimes unavoidable. Use common sense
    "PLR0913",  # Too many arguments. Sometimes unavoidable. Use common sense
    "PLR0915",  # Too many statements. Sometimes unavoidable. Use common sense
    "TD002",    # Missing author in TODO
    "TD003",    # Missing link in TODO
    "C901",     # Too complex code. Sometimes unavoidable. Use common sense
    "E402",     # Module level import not at top of file. Often needed for conditional dependencies
    "CPY001",   # We don't use per-file copyrights

    "PLR0917",  # Too many positional arguments. Nothing to do for this kind of a library
    "FBT001",   # The library tries to match the API. So boolean-typed positional args are OK
    "FBT002",   # Same as FBT001, but for keyword args
    "FIX002",
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = [
    "S101",     # Use of assert is expected in tests
    "S105",     # hardcoded secrets in tests are OK
    "S106",     # hardcoded secrets (func args) in tests are OK
    "S107",     # hardcoded secrets (func arg defaults) in tests are OK
    "PLR2004",  # Magic values in test assertions are expected
]
