name: CI Pipeline

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v.*.*.*"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.11", "3.12"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python v${{matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version}}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: true
      - name: Install nox
        run: pip install nox
      - name: Run tests
        run: nox -s tests --no-error-on-missing-interpreters
      - name: Run linting
        run: nox -s lint --no-error-on-missing-interpreters
      - name: Run coverage
        run: nox -s coverage --no-error-on-missing-interpreters
      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
